### PR TITLE
Improve noise wiki with Tree generator example and zoomable noise

### PR DESCRIPTION
**Pull request by PutawanDE**
# Improve Noise Wiki with Tree Generator Example and Zoomable Noise

GCI Task: Improve world generation tutorial: noise - MovingBlocks

## Contains
- Improve noise wiki: https://github.com/PutawanDE/TutorialWorldGeneration/wiki/
- Tree generator code sample which uses white noise
- Add zoom noise configuration menu to mountain, allowing for adjusting the zoom used in SubSampledNoise
- Images to use in Wiki

whitenoise2

### CODE REVIEW

**Comment by Cervator** [comment]
Very nice work! One thing I may suggest: If you commit the images to the wiki repo instead of the code repo you can keep them out of this PR and let the code repo remain smaller :-)

Only other thing that sticks out to me (within serious testing) is that you've got a bunch of "magic numbers" in the `Tree` class - but since it is already a container maybe just having the number in a method getting for that characteristic is about as good as having default constants and that's just what the getters return. So that may be a non-issue, even if it maaaay be slightly easier to just check a bunch of numbers at the top ... decisions decisions.

**Comment by Cervator** [comment]
Update from a GCI comment - further suggestions for the wiki:

* In a few spots you link together pages, but sometimes very briefly and abruptly even simply leaving a link at the bottom of the page. Think a bit more closely about how to start and end pages and try to ease in and out of the topic. Consider if it might make sense to have a nice little widget of sorts at the top of each noise-related page as a sort of table of contents for the different  pages. Could be as simple as some "| Link 1 | Link 2 | Link 3 ..." one liner that's nicely formatted
* There are occasional typos and odd grammar, it would be nice if you could have a few people read through it and "copy edit" it for further improvements. You could probably recruit a few people off chat if you ask nicely occasionally, or maybe drag some friends into checking on it
* The "Noise Application" page is still very long, partially thanks to the awesome images. Maybe you can find ways to cut it into a few pieces, especially if you have a nice little index header on each involved page to make it easier to jump around?

**Comment by PutawanDE** [comment]
I made the update.
- Remove the magic numbers in `Tree`, add constants
- Fix typos and grammar in Wiki
- Separate "Noise Application" page into 2 pages: "Noise in World Generation" and "Noise implementation".
- Noise-related links at the top of each Noise page - one liner

**Comment by syntaxi** [comment]
To reiterate what Cervator said, images should be in the wiki rather than the code repo. That way they don't bloat both this PR and the repo itself.

I've got a few grammatical queries/issues:

* In the **"How does the Noise Work"** section of the overview you say _'[...] in this tutorial we use `SimplexNoise` to generate [...]'_. However you then refer only to Perlin from that point on. It's also, uh, not much of a rolling hill tutorial.
* _'[...] generation, the brigther the area [...]' brigther -> brighter
* _'[...] In this tutorial, this technique is used to create mountains [...]'_ I think that this along with the prior occurrence of 'tutorial' would be better off saying "later on we will use".
* _'[...] we multiple the [...]'_ multiple -> multiply
* _'[...] We compare if that random number at the specific coordinate is more than 0.99, then we place a tree. [...]'_ -> "We compare the noise at that point to our threshold, 0.99, and only place a tree if it's higher."
* _'[...] Please head to Noise Implementation page. [...]'_ -> "to the Noise Implementation Page"
And a few other points:

* I am not sure if this is because of how the wiki is a fork but I can't see a reference to the noise pages on the main page anywhere. It would be good to have a link to the overview there.

* _'[...] WhiteNoise: use for plants and floras [...]'_ -> "Use for placing discrete things randomly in the world. For instance, houses & trees. Things you just want to evenly cover the area in"
*_'[...] use to get smoother terrain by gradually get to various random values. [...]'_ -> "use to smooth out the above noises by "zooming in" or "stretching" the values out".
* In this **"Summary - Which noise to use?"** I would swap brownian and white noise so you have the three distinct noise types at the top, then the three noise types that alter them at the bottom.

* _'[...] octaves is used to determine how many noise maps (functions) - in this case PerlinNoise - to be combined to form 1 single noise map. So, more octaves, more noise maps combined, more details and more calculation. [...]'_ -> this section both doesn't read very well and doesn't seem fully correct. From my understanding you've just said "octave is a multiplier that increases the amplitude of the noise" but in a more convoluted fashion.

**Comment by PutawanDE** [comment]
https://github.com/PutawanDE/TutorialWorldGeneration/wiki

- Remove the images from this PR
- Fix typos and grammars queries/issues
- Add Noise reference into **Home** page under **"More Advanced"**
- Rearrange in **"Summary - Which noise to use?"**
- Improve explanation for **octave**
- Add/Edit explanation for **WhiteNoise** and **SubSampledNoise** as suggested

**Comment by syntaxi** [comment]
Looks good then.
I'm gonna merge this PR and give you edit rights on the wiki. Feel free to copy over your changes in your own time

**Pull request merged**
